apiVersion: templates.tsm.vmware.com/v1
kind: HealthCheck
metadata:
  labels:
    projectId: default
  name : <name>-healthcheck
spec:
  name: <name>-healthcheck 
  protocol: HTTP
  domain: acme.<FQDN.com>
  port: 3000
  path: "/"
  healthThreshold: 3
  certificate_id: ''
  external_port: 80
  interval: 10
