# Configure Public Service
apiVersion: gns.tsm.vmware.com/v1
kind: PublicService
metadata:
  labels:
    gnsId: acmecli
    projectId: default
  name: acme.vtechk8s.com 
spec:
  external_port: 80
  external_protocol: HTTP
  fqdn: acme.vtechk8s.com
  gslb:
    type: ROUND_ROBIN
  ha_policy: ''
  ingress_on_internal_gateways: true
  name: acme
  public_domain:
    certificate_id: ''
    external_dns_id: fbe82725-c680-4bba-9ea5-5fdd46860091
    primary_domain: vtechk8s.com
    sub_domain: acme
  ttl: 100
  wildcard_certificate_id: ''
  healthcheck_ids:
  - acme-vtechk8s-healthcheck 
---
# Configure Public Service Route
apiVersion: gns.tsm.vmware.com/v1
kind: PublicServiceRoute
metadata:
  labels:
    projectId: default
    gnsId: acmecli
    fqdn: acme.vtechk8s.com
  name : shopping.3000
spec:
  paths:
  - "/"
  target: shopping
  target_port: 3000