# Configure Public Service
apiVersion: gns.tsm.vmware.com/v1
kind: PublicService
metadata:
  labels:
    gnsId: <GNS-NAME>
    projectId: default
  name: acme.<FQDN.com> 
spec:
  external_port: 80
  external_protocol: HTTP
  fqdn: acme.<FQDN.com>
  gslb:
    type: ROUND_ROBIN
  ha_policy: ''
  ingress_on_internal_gateways: true
  name: acme
  public_domain:
    certificate_id: ''
    external_dns_id: fbe82725........ #get from TSM API
    primary_domain: <FQDN>.com
    sub_domain: acme
  ttl: 100
  wildcard_certificate_id: ''
  healthcheck_ids:
  - <name>-healthcheck 
---
# Configure Public Service Route
apiVersion: gns.tsm.vmware.com/v1
kind: PublicServiceRoute
metadata:
  labels:
    projectId: default
    gnsId: <GNS-NAME>
    fqdn: acme.<FQDN.com>
  name : shopping.3000
spec:
  paths:
  - "/"
  target: shopping
  target_port: 3000
